version: '3.3'
services:
  backend:
    build: ./Backend
    networks: 
      - app-network
    depends_on:
      - database
  database:
    build: ./Database
    networks:
      - app-network
  httpd:
    build: ./HttpServer
    ports: 
      - "80:80"
    networks:
      - app-network
    depends_on: 
      - database
      - backend
networks:
  app-network: